version: '2.1'
services:
    transmission:
        env_file:
            - .env
        image: lscr.io/linuxserver/transmission:latest
        container_name: transmission
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Etc/UTC
            - USER=$TRANSMISSION_USERNAME
            - PASS=$TRANSMISSION_PASSWORD

        volumes:
            - '$TRANSMISSION_DOWNLOAD_DIR:/downloads'
            - './.transmission/config:/config'
            - '/tmp/transmission/watch:/watch'
        ports:
            - '$INTERNAL_TRANSMISSION_PORT:9091'
            - 51413:51413
            - 51413:51413/udp
        restart: unless-stopped
